### ISSUE TITLE
I can't read the data after connecting to Arduino

### ISSUE THREAD

**Issue by zeynepozcan** [mhamilt/maxmsp-ble#33]
I'm trying Max-BLE with Sonoma 14.2.1 | Apple M2 Max | Max 8.5.5 | Arduino IDE 2.2.1.
 I can connect the Arduino to MAX after scanning with the Max-BLE object, but I cannot read the data or any serial message coming from Arduino. I'm working with the Seeed Xiao nRF52840 Sense BLE.

**Comment by mhamilt** [comment]
@zeynepozcan  If you have a look around with something like [LightBlue](https://apps.apple.com/gb/app/lightblue/id557428110) are you able to see anything?

**Comment by zeynepozcan** [comment]
Yes, I am able to connect to the board with the LightBlue app both on iOS and macOS. I'm not sure if that app is designed to read and report serial print values, but it can toggle the on-board LED. Similarly, max-ble can discover and connect to the board. I'm just unable to read the serial print outs. I might be missing an instruction to dump those out from the max-ble object.

**Comment by mhamilt** [comment]
@zeynepozcan Do you have a minimal example of the Arduino sketch? Perhaps in a gist?

I don't follow the 'serial prints' you are trying to read I'm afraid.

**Comment by zeynepozcan** [comment]
@mhamilt, I am simply reading data off of the on-board IMUs and printing them out with a Serial.print() in my own code, but to give a simpler example: using the ble-notify.ino example included in this repository, I am unable to see the output of the following line in Max:
Serial.println(((ledState) ? "On" : "Off"));
Is it possible to monitor these "on" and "off" strings in Max over BLE? If I connect the board over USB, I can see these in Max through the serial object with the USB port selected, but I can't read these over BLE with neither the max-ble object nor the serial object (with the input set to the Bluetooth port).

**Comment by mhamilt** [comment]
@zeynepozcan  I think I see now.

Yes, your suspicion is correct and sadly you cannot send values over BLE with the `Serial` interface.

BLE is not really built for serial communication, though you can sort of cobble something together that is _close_ to serial comms. 

You can subscribe to a characteristic via the `max-ble` and write values to that characteristic in your sketch. Be aware that you are probably going to drop the odd value here and there. You will also likely have to limit how quickly you are writing data.

Most of the time you will just want to forward on some sensor data. Rather than dealing with text I would look at trying to send some `1`s and `0`s. In fact I believe the [example sketch](https://github.com/mhamilt/maxmsp-ble/blob/master/max-package/max-ble/extras/ble-notify/ble-notify.ino) sends a `1` or a `16` (i.e. `0x10`) value 

https://github.com/mhamilt/maxmsp-ble/blob/3dee7ac622c4edf05cbbd69481d1c8b912b20474/max-package/max-ble/extras/ble-notify/ble-notify.ino#L64

which you can then use the [`byte-cast` object](https://github.com/mhamilt/max-byte-cast/tree/2ac8a1d2fd30c2e3ced798e9024dd4933c773cdf) to help interpret

That said, I think I may need to build an Apple Silicon release of that object. I will get on that some point in the next week.

EDIT: I _do_ need to build for Apple Silicon, but if you are just using 8-bit integers then you are fine and should be able to use [iota](https://docs.cycling74.com/max8/refpages/itoa)

**Comment by zeynepozcan** [comment]
Thank you, @mhamilt. Currently, I am using the customCharacteristic.writeValue() function and occasionally, I need to send a bang to the "read index" to receive the raw bytes. Otherwise, the reception stops.

**Comment by mhamilt** [comment]
@zeynepozcan That sounds about right. Polling for data, as you are doing, is one option. You can also set the characteristic as "notifying" and then "subscribe" to it. That should give you fairly instantaneous results. You shouldn't need to worry about device connection at that point
